ovrlib/pa: client for PA
vote/state-registration-apis pull request #1
Opened 2020-06-23 21:37 UTC by liewegas

2020-06-25 15:48 UTC, benweissmann requested changes
This looks great! I have a bunch of comments mostly around ways that I think we can make this more useful to other groups.

I also think that having a really simple CLI (in a separate file) would be helpful in terms of providing something that people can use out-of-the-box to test their API key, etc.

2020-06-25 15:48 UTC, benweissmann commented on ovrlib/pa.py
> +        if root.tag == "RESPONSE":
We were seeing that incomplete requests would return something without an error, but also no registration ID, right? Should we throw an error for that case?

2020-06-25 15:48 UTC, benweissmann commented on ovrlib/pa.py
> +    def fetch_constants(self):
Should we return some data structure here rather than printing? We can have a little CLI in a separate file to print out the data, but it'd be nice for this to return a machine-readable data structure if someone wants to, e.g., do validation or render UI dropdowns based on this.

2020-06-25 15:48 UTC, benweissmann commented on ovrlib/pa.py
> +            "united-states-citizen": "1",
I'm a little nervous about always setting these to "1" -- I think forcing people to pass in `will_be_eighteen_on_election_day: True, us_citizen: True, made_declarations: True` and then erroring if those values aren't passed is a good way to reinforce that those are things you have to render in the UI and have the user agree to.

2020-06-25 15:48 UTC, benweissmann commented on ovrlib/pa.py
> +            "united-states-citizen": "1",
As a bonus, if we define like `to_request_body()` on the dataclass, then library users who don't want to use this library for the request logic (and just want to use it for the PITA part of assembling a valid request) can just import the dataclass, instantiate it, and call `data.to_request_body()` to get a valid request body.

2020-06-25 15:48 UTC, benweissmann commented on ovrlib/tests/test_pa.py
> +@pytest.mark.parametrize(
I think it'd also be useful to have one or two end-to-end tests using [responses](https://github.com/getsentry/responses) would be valuable here

2020-06-25 15:48 UTC, benweissmann commented on ovrlib/tests/test_pa.py
> +@pytest.mark.parametrize(
Also a test of `fetch_constants`

2020-06-25 15:48 UTC, benweissmann commented on ovrlib/pa.py
> +UNIT_TYPE = {
Are these constants from the PDF? Or coming from the API? Would be good to document where these came from and how to update them.

2020-06-25 15:48 UTC, benweissmann commented on ovrlib/pa.py
> +class ReadOnlyAccessKeyError(Exception):
Is this thrown somewhere? I definitely think surfacing this error in particular with some message like "please email your point-of-contact at the Pennsylvania Secretary of State's office to upgrade your API key to read-write access" would be good, given that this is an issue we ran into.

2020-06-25 15:48 UTC, benweissmann commented on ovrlib/pa.py
> +                # NOTE: the API enumerates specific suffixes; not sure what happens if we
Can we test this out?

2020-06-25 15:53 UTC, nickcatal reviewed
Building on top of @benweissmann's comments, here are my much more mundane style comments

2020-06-25 15:53 UTC, nickcatal commented on ovrlib/pa.py
> +        print("GENDER = %s\n" % json.dumps(gender, indent=4))
`print` here and elsewhere

Probably not the world's worst idea to use `logger.debug` here instead of removing the print outright

2020-06-25 15:53 UTC, nickcatal commented on ovrlib/pa.py
> +        Submit a voter registratio
missing a `n`

2020-06-25 15:53 UTC, nickcatal commented on ovrlib/pa.py
> +        if addr.get("unittype") is not None or addr.get("unitnumber") is not None:
Do you ever see `unittype` or `unitnumber` ever being a falsy value?

If not, I think this can just be `if addr.get("unittype") or addr.get("unitnumber")`

2020-06-25 15:53 UTC, nickcatal commented on ovrlib/pa.py
> +            m = re.compile(r"^#?(\d+)$").match(addr["address2"].strip())
We probably want to do all these `re.compile` steps when python first loads the module (thus have them above the class) then do just the matching using the pre-compiled regex inside the class.

Regex compiling can be kinda intense and doesn't need to be done on a per-registration basis, so we can front-load it to when python first launches.

2020-06-25 15:53 UTC, nickcatal commented on ovrlib/pa.py
> +class InvalidAccessKeyError(Exception):
Do we want all of these to inherit from a master `OVRLibException`? We also may want these in a separate `exceptions.py` file

2020-06-25 19:14 UTC, benweissmann requested changes
Sorry, I had one more larger comment from before that it looks like I didn't actually hit save on:

I think we should use [MyPy](http://mypy-lang.org/) here and use [dataclasses](https://docs.python.org/3/library/dataclasses.html) instead of dicts for our inputs/outputs. I think this will help with a couple of things when other folks go to use this library:

- We're going to need to document the structure of the input/output dictionaries somewhere, so we might as well do that in a way that mypy can type-check (I think sphinx can auto-generate good docs based on type hints / dataclasses)

- If whoever's using this library is also using mypy, they'll get nice compile-time errors if they mess up any of the data structures

As another plus, I think that can help break this up a bit -- we can create three dataclasses in separate files: `PAOVRRequest`, `PAOVRResponse`, and `PAOVRConstants` that will enumerate all the required/option fields, and we can implement `to_request_body()` on `PAOVRRequest`, `from_response_body()` on `PAOVRResponse`, and `from_response_bodies()` on `PAOVRConstants`.

If you haven't used mypy before, it can have a bit of a learning curve (the [vscode python extension](https://code.visualstudio.com/docs/python/linting) helps a lot), so lmk if you want to pair! There's some examples of where we've used them to document and validate complex data structures in the [fax gateway](https://github.com/vote/fax_gateway/blob/master/app/helpers/messages.py) and [Turnout](https://github.com/vote/turnout/blob/ab6bcaca9f8d448606964085112451c37c17e90c/app/common/pdf/pdftemplate.py#L16).

2020-06-26 15:30 UTC, liewegas commented
Moved to dataclasses, except for the constants: dataclasses don't like default values that are mutable dicts/lists/etc.

Also added mypy and type notations

2020-06-29 14:09 UTC, benweissmann approved these changes
Looks great! Methods just need return type annotations (e.g. `get_election_info(self) -> PAOVRElectionInfo:`)

2020-06-29 19:45 UTC, merged